destination:    ./_site/
lsi:            false
markdown:       kramdown
pygments:       false
permalink:      /:categories/:title
static_root:    "https://w15ydotcom.hasacdn.net/20111230"
static_root:    "/static"
tag_root:       /tags
